spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/educhallenge}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
app.security.jwt.secret=${APP_SECURITY_JWT_SECRET:educhallenge-super-secret-key-change-me-1234567890}
app.security.jwt.expiration=${APP_SECURITY_JWT_EXPIRATION:PT12H}
